name: Trigger Netlify Build
on:
  schedule:
    # Every 2 hours on UTC
    - cron: '58 1,3,5,7,9,11,13,15,17,19,21,23 * * *'
jobs:
  build:
    name: Netlify build
    runs-on: ubuntu-latest
    steps:
      - uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Bangkok
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5f82a598d1e6201d4ec0cb7a
      - name: Show current date
        run: date
